# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b3cf4f693a0aae4189bd83aa6a84dfcb5eb41795bc62e627c7d83b63d4ad45640095db98141d194dc2096ae6d0b6bb7ccc10bc81139b59e0aab84211f79cdaa

test:
  secret_key_base: fba53e861cef1a8e62dd3796b03f15e01cb482b7048775371df572a9ae6797c14072ecb9b45675da4fa6111f97359173169e76207aac788b5766a1ce50f1c2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
